<?php
$RESULTDATACOUNT=0;
	$results=null;
	$firstload=true;
	$resultData=array();
	$startn=1;
	$pageno=1;
	$rowNo=1;
	if(isset($_REQUEST["page"]))
	{
		$pageno=$_REQUEST["page"];
		if($pageno<1) 
			$pageno=1;
		if($pageno>$MAXPAGENOS)
		{
			$startn=floor(($pageno/$MAXPAGENOS))*$MAXPAGENOS;
			if(($pageno % $MAXPAGENOS)==0 )
				$startn=($startn-$MAXPAGENOS)+1;
			else
				$startn=$startn+1;
			if($startn<=0)
				$startn=1;
		}
		else
			$startn=1;
		$firstload=false;
	}
	elseif(isset($_REQUEST["prev"]))
	{
		$pageno=$_REQUEST["prev"];
		if($pageno<1) 
			$pageno=1;
		if($pageno>$MAXPAGENOS)
		{
			$startn=($pageno/$MAXPAGENOS);
			$startn=floor($startn)*$MAXPAGENOS+1;
			$startn=$startn-$MAXPAGENOS;
			if($startn<=0)
				$startn=1;
		}
		else
			$startn=1;
		$firstload=false;
	}
	elseif(isset($_REQUEST["next"]))
	{
		$pageno=$_REQUEST["next"];
		if($pageno<1) 
			$pageno=1;
		if($pageno>$MAXPAGENOS)
		{
			$startn=($pageno/$MAXPAGENOS);
			$startn=floor($startn)*$MAXPAGENOS+1;
			if($startn<=0)
				$startn=1;
		}
		else
			$startn=1;
		$firstload=false;
	}
?>